### PR TITLE
Deprecated numpy datatypes

### PR DESCRIPTION
**Pull request by friggog**
Numpy update deprecated np.bool completely

### CODE REVIEW

**Comment by AKuederle** [comment]
Great! I was starting to get annoyed by the deprecation warnings :D

**Review by AKuederle — CHANGES_REQUESTED** [review]
Looks good!

In the tests I saw another numpy deprecation warning:

https://github.com/EmbodiedCognition/py-c3d/actions/runs/3730058991/jobs/6326668934#step:5:8

Do you know where this is caused/if we can fix it?

**Comment by friggog** [comment]
@AKuederle think I have tracked it down and fixed

**Comment by AKuederle** [comment]
Seems like the warning is still there, but now it is thrown by a internal numpy function. Aka not our problem anymore.

Thanks for updating this!

**Review by AKuederle — APPROVED** [review]

**Comment by AKuederle** [comment]
@friggog 0.5.2 published on Pypi

**Pull request merged**
